### ISSUE TITLE
having trouble running examples

### ISSUE THREAD

**Issue by sliutheory** [tnecio/supercell-core#4]
Hi. 
First, thank you for developing this tool. 
When I would like to try it out, somehow all scripts in the Example failed to work. 

python3 graphene_nips3.py
returns following error

    if len(line) != len(atomic_species):
TypeError: object of type 'NoneType' has no len()

running the example NiPS3 example

    nips3 = sc.read_POSCAR("./data/POSCAR_NiPS3",["Ni", "P", "S"])
TypeError: read_POSCAR() takes 1 positional argument but 2 were given

**Comment by tnecio** [comment]
Usage example in the README was outdated, I fixed it now. Examples in examples/ directory should be OK

**Comment by tnecio** [comment]
Thanks, the examples in README.md and in examples/graphene_nips3.py were outdated, I fixed them now
